[package]
name = "Lambda-Rubiks-Cube"
version = "0.1.0"
authors = ["kletska <kletska.epa@hotmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"

[build-dependencies]
lalrpop = "0.19.6"